# Generated by Django 5.0.6 on 2024-08-06 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcenter',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='appeal_phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='learning_centers/'),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='manager_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
