# Generated by Django 5.0.6 on 2024-08-13 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcenter',
            name='manager_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
