# Generated by Django 5.0.6 on 2024-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_learningcenter_manager_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCenterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learningCenterId', models.IntegerField()),
                ('balance', models.FloatField()),
                ('studentId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningCenterGroupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learningCenterDetailID', models.IntegerField()),
                ('learningCenterGroupId', models.IntegerField()),
                ('dailyPayment', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('studentAge', models.IntegerField()),
                ('studentPhone_number', models.CharField(max_length=20)),
                ('studentImage', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('learningCenterIDsList', models.JSONField(default=list)),
                ('parentId', models.IntegerField()),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=100)),
                ('teacherPhone_number', models.CharField(max_length=20)),
                ('teacherImage', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('teacherBio', models.TextField()),
                ('teacherAge', models.IntegerField()),
                ('learningCenterIDsList', models.JSONField(default=list)),
            ],
        ),
    ]
