# Generated by Django 5.0.6 on 2024-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_learningcenterdetails_learningcentergroupstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leaningCenterName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
