# Generated by Django 5.0.6 on 2024-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_requesttoapply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcentergroupstatus',
            old_name='dailyPayment',
            new_name='paymentAmount',
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='login',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcenterdetails',
            name='debt',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcentergroupstatus',
            name='lastPayedMonth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcentergroupstatus',
            name='lastPayedYear',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcentergroupstatus',
            name='learningCenterID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcentergroupstatus',
            name='paymentMonthlyPeriod',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcentergroupstatus',
            name='status',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcentergroupstatus',
            name='studentID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
