# Generated by Django 5.0.6 on 2024-08-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_remove_learningcentergroupstatus_paymentmonthlyperiod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='learningCenterIDsList',
        ),
    ]
