# Generated by Django 5.0.6 on 2024-08-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_remove_student_learningcenteridslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatherName', models.CharField(max_length=250)),
                ('motherName', models.CharField(max_length=250)),
                ('fatherPhone', models.CharField(max_length=250)),
                ('motherPhone', models.CharField(max_length=250)),
                ('fatherImage', models.CharField(max_length=250)),
                ('motherImage', models.CharField(max_length=250)),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
