# Generated by Django 5.0.6 on 2024-08-27 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcenter',
            name='userType',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
