# Generated by Django 5.0.6 on 2024-08-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_student_usertype_teacher_login_teacher_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcenterID', models.IntegerField()),
                ('branchLocation', models.CharField(max_length=1000)),
                ('branchImage', models.ImageField(blank=True, null=True, upload_to='branch-images/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=250)),
                ('courseImage', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('courseBio', models.TextField()),
                ('courseCategory', models.CharField(max_length=250)),
                ('lcenterID', models.IntegerField()),
                ('minStudent', models.CharField(max_length=250)),
                ('studentList', models.CharField(max_length=250)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=300)),
                ('groupImage', models.CharField(max_length=300)),
                ('roomId', models.IntegerField()),
                ('chatId', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('lcenterID', models.IntegerField()),
                ('courseId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcenterID', models.IntegerField()),
                ('roomName', models.CharField(max_length=300)),
                ('roomLocationBio', models.TextField()),
                ('branchID', models.IntegerField()),
            ],
        ),
    ]
